### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by majorsl** [mkuron/letsencrypt-mac#2]
Hello, this looks like an awesome tool to use! I've tested doing most of this manually or semi-automated using certbot.

I decided to use this, but am running into a wall.  Is there any extra configuration that is needed with the letsencrypt script or does your script pass along all the needed values?  Here's what I'm seeing:

```
+ ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 403)

Details:
{
  "type": "urn:acme:error:unauthorized",
  "detail": "No registration exists matching provided key",
  "status": 403
}www.themajorfamily.net server3.themajorshome.com.3E36D6D0707B2BEA4800F171243C91C0DF67C2D6 /Users/majorsl/themajorfamilynet
# INFO: Using main config file /Users/majorsl/Scripts/letsencrypt/config
Processing www.themajorfamily.net
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for www.themajorfamily.net...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 403)
```

**Comment by mkuron** [comment]
That message comes from the server, not from my script. I suspect Let's Encrypt has changed something about their API as letsencrypt.sh (now dehydrated) has a couple recent commits that deals with similar issues. Please pull my latest commits and try again. Note that letsencrypt.sh has been renamed to dehydrated, but my use of it as a git submodule shouldn't be harmed by that.

I just tested it on my domain and it fetched a new certificate just fine. If it doesn't work for you, perhaps check recent issues reported on [dehydrated](https://github.com/lukas2511/dehydrated).

**Comment by majorsl** [comment]
Ah, I suspected that. I updated to dehydrated before your commits. I will try again and report back.

Thank you for doing the work on this, getting the certs into Server.app is the tricky part. I semi automated it shortly after my post, but your solution is so much better than mine.

**Comment by majorsl** [comment]
My first site worked perfectly, the 2nd failed with:

```
www.themajorshome.com www.themajorshome.com.4EF3CEB86143FEB89FE9EE880706C862F25B748F /Users/majorsl/Sites
# INFO: Using main config file /Users/majorsl/Scripts/letsencrypt/config
Processing www.themajorshome.com
 + Signing domains...
 + Creating new directory /Users/majorsl/Scripts/letsencrypt/./dehydrated/certs/www.themajorshome.com ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for www.themajorshome.com...
 + Responding to challenge for www.themajorshome.com...
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to www.themajorshome.com",
    "status": 400
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/dIYMNxGrbctMpdCrmD8_eToTVG0gZ1NlbX7Dk0KxYvA/300570956",
  "token": "ce794NS2tab8ALoAT0DYWyL6TRJaBTRnVq-ZCsKoiGw",
  "keyAuthorization": "ce794NS2tab8ALoAT0DYWyL6TRJaBTRnVq-ZCsKoiGw.b4-9ssC1n9GmdI18xvAkae6as3dvY_seo3WlxJc497k",
  "validationRecord": [
    {
      "url": "http://www.themajorshome.com/.well-known/acme-challenge/ce794NS2tab8ALoAT0DYWyL6TRJaBTRnVq-ZCsKoiGw",
      "hostname": "www.themajorshome.com",
      "port": "80",
      "addressesResolved": [
        "72.43.24.138"
      ],
      "addressUsed": "72.43.24.138"
    }
  ]
})
```

Interestingly, it tried on port 80 which I don't have configured - thought it would try on 443.  I had successfully done the challenge with certbot on that one, so I know it's available.

Side question: I note that when a cert is updated, the old one isn't removed from Server.app.  Is that normal and does Server.app automatically use the cert with the longest expiry date?

**Comment by mkuron** [comment]
Try turning on Port 80 for a new website with the same hostname(s)  and configure a redirect to HTTPS on 443. That's kind of an implicit assumption I made anyway.

When a new certificate is installed, it is assigned to the web site via its fingerprint, but the old one is not deleted from Keychain. I might add that in thhe future, but for now you can manually delete the old certificates from Server.app (though their presence does no harm).

**Comment by majorsl** [comment]
Yup, that did it. Perfect. I agree, no harm on the multiple certs.

I'm on Server 5.2 and 10.12.  I noted that when it ran, coincidently, my server refused http connections afterwards on the above (failed) run.  I had to stop/start the service again to restore.

Of course, now that I've tested it, I don't have any certs to renew since the one that was failing was my test domain with a manual run of certbot and didn't see the issue.

For now, I'm happy to let it be and will start a new issue if I see it happen again in a couple of months.  Just thought I'd note that one anomaly.

Again, thank you for this script!

**Comment by majorsl** [comment]
I'm not sure what happened, but running for renewal has hosed my www so badly that it won't even start anymore.  I'm still trying to sort this out.  Whatever is happening, this process is no longer safe to use.

**Comment by mkuron** [comment]
Worked fine for me just days ago on macOS 10.11.6. The only problem I've ever seen was that the Port 80 site had HTTPS enabled after running, which caused the webserver not to start up anymore. The Apache error log gives a clear error message in that case though. Also, that problem isn't even specific to my procedure, but has also happened to me after editing the port 80 site in Server.app.

**Comment by majorsl** [comment]
Yes, I found that a little while ago. I moved on to the straight certbot renew method with a post renew script that adds the certs to Server. Not as slick as what you're doing, but for my needs it'll be okay. I think. Thanks!
