### ISSUE TITLE
dehydrated "No such file or directory"

### ISSUE THREAD

**Issue by Tazintosh** [mkuron/letsencrypt-mac#3]
Good evening,

I've just downloaded and unzip "letsencrypt-mac-master.zip" on my Download folder.
I've run the following on the Terminal:
`sudo /Users/MyUser/Downloads/letsencrypt-mac-master/run.sh`

After logging my website under https, I got the following error:
`/Users/MyUser/Downloads/letsencrypt-mac-master/run.sh: line 32: /Users/MyUser/Downloads/letsencrypt-mac-master/dehydrated/dehydrated: No such file or directory`

Any idea?
Running macOS Sierra 10.12.5 with Server.app 5.3.1

Thanks in advance for your time and support.

**Comment by mkuron** [comment]
Dehydrated is used as a Git submodule. That means you need to either do a recursive clone of my repository, or download a dehydrated zip file and extract that into the same folder.

**Comment by Tazintosh** [comment]
Thanks!
