### ISSUE TITLE
Error: "JWS has no anti-replay nonce"

### ISSUE THREAD

**Issue by mringwal** [mkuron/letsencrypt-mac#7]
Hi. I've been running your script on a macOS X server and it just stopped working with this'

 + Requesting challenge for mydomain.omh...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 400)

Details:
{
  "type": "urn:acme:error:badNonce",
  "detail": "JWS has no anti-replay nonce",
  "status": 400
}

Updating the dehydrated script to v0.6.5 got it working again.

Could you update the dehydrated submodule?

Thanks!

**Comment by mkuron** [comment]
Update in 79a1575. However, the way I read https://github.com/lukas2511/dehydrated/issues/684 and https://community.letsencrypt.org/t/jws-has-no-anti-replay-nonce/103324/18, this is actually a server-side connection issue. Just retrying a couple times should eventually give you your certificates.

**Comment by mringwal** [comment]
Thanks. Small dataset: The day before yesterday, I got the error 5 times. Yesterday, I've tried 3 times. Then, I've updated dehydrated and it worked the first time. Maybe there's also an temporary server error, but it didn't seem to work at all before. Anyway, looks good now :)

**Comment by mkuron** [comment]
Ah, they‘re also shutting down the old v1 API: https://letsencrypt.status.io/pages/maintenance/55957a99e800baa4470002da/5d9f830b1c84d208a53afac3. That‘s a separate thing though and would have given a different error message.
